version: 1  
disable_existing_loggers: False  
formatters:  
  default:  
    format: '%(asctime)s - %(message)s'  
handlers:  
  console:  
    class: logging.StreamHandler  
    formatter: default  
    level: INFO  
  file:  
    class: logging.handlers.RotatingFileHandler  
    formatter: default  
    filename: logs/app.log  
    maxBytes: 10485760  # 10 MB  
    backupCount: 5  
loggers:  
  uvicorn:  
    handlers: [console, file]  
    level: INFO  
    propagate: False  
  uvicorn.error:  
    handlers: [console, file]  
    level: INFO  
    propagate: False  
  uvicorn.access:  
    handlers: [console, file]  
    level: INFO  
    propagate: False  
  __main__:  
    handlers: [console, file]  
    level: INFO  
    propagate: False  
root:  
  handlers: [console, file]  
  level: INFO  